// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SequenceTopic int32

const (
	SequenceTopic_sequence_V1 SequenceTopic = 0
)

var SequenceTopic_name = map[int32]string{
	0: "sequence_V1",
}
var SequenceTopic_value = map[string]int32{
	"sequence_V1": 0,
}

func (x SequenceTopic) String() string {
	return proto.EnumName(SequenceTopic_name, int32(x))
}
func (SequenceTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_example_67be0b3ec67f689b, []int{0}
}

type SequenceRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SequenceRequest) Reset()         { *m = SequenceRequest{} }
func (m *SequenceRequest) String() string { return proto.CompactTextString(m) }
func (*SequenceRequest) ProtoMessage()    {}
func (*SequenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_67be0b3ec67f689b, []int{0}
}
func (m *SequenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SequenceRequest.Unmarshal(m, b)
}
func (m *SequenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SequenceRequest.Marshal(b, m, deterministic)
}
func (dst *SequenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceRequest.Merge(dst, src)
}
func (m *SequenceRequest) XXX_Size() int {
	return xxx_messageInfo_SequenceRequest.Size(m)
}
func (m *SequenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceRequest proto.InternalMessageInfo

func (m *SequenceRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SequenceRequest) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type SequenceCore struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Sequences            []string `protobuf:"bytes,3,rep,name=sequences,proto3" json:"sequences,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SequenceCore) Reset()         { *m = SequenceCore{} }
func (m *SequenceCore) String() string { return proto.CompactTextString(m) }
func (*SequenceCore) ProtoMessage()    {}
func (*SequenceCore) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_67be0b3ec67f689b, []int{1}
}
func (m *SequenceCore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SequenceCore.Unmarshal(m, b)
}
func (m *SequenceCore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SequenceCore.Marshal(b, m, deterministic)
}
func (dst *SequenceCore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceCore.Merge(dst, src)
}
func (m *SequenceCore) XXX_Size() int {
	return xxx_messageInfo_SequenceCore.Size(m)
}
func (m *SequenceCore) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceCore.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceCore proto.InternalMessageInfo

func (m *SequenceCore) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SequenceCore) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *SequenceCore) GetSequences() []string {
	if m != nil {
		return m.Sequences
	}
	return nil
}

type SequenceResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Quantity             int64    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Sequences            []string `protobuf:"bytes,4,rep,name=sequences,proto3" json:"sequences,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SequenceResponse) Reset()         { *m = SequenceResponse{} }
func (m *SequenceResponse) String() string { return proto.CompactTextString(m) }
func (*SequenceResponse) ProtoMessage()    {}
func (*SequenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_67be0b3ec67f689b, []int{2}
}
func (m *SequenceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SequenceResponse.Unmarshal(m, b)
}
func (m *SequenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SequenceResponse.Marshal(b, m, deterministic)
}
func (dst *SequenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceResponse.Merge(dst, src)
}
func (m *SequenceResponse) XXX_Size() int {
	return xxx_messageInfo_SequenceResponse.Size(m)
}
func (m *SequenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceResponse proto.InternalMessageInfo

func (m *SequenceResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SequenceResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SequenceResponse) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *SequenceResponse) GetSequences() []string {
	if m != nil {
		return m.Sequences
	}
	return nil
}

func init() {
	proto.RegisterType((*SequenceRequest)(nil), "pb.SequenceRequest")
	proto.RegisterType((*SequenceCore)(nil), "pb.SequenceCore")
	proto.RegisterType((*SequenceResponse)(nil), "pb.SequenceResponse")
	proto.RegisterEnum("pb.SequenceTopic", SequenceTopic_name, SequenceTopic_value)
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_example_67be0b3ec67f689b) }

var fileDescriptor_example_67be0b3ec67f689b = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0xe2, 0x49,
	0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x88, 0x28, 0xd9, 0x73, 0xf1, 0x07, 0xa7, 0x16, 0x96, 0xa6,
	0xe6, 0x25, 0xa7, 0x06, 0x81, 0xe8, 0xe2, 0x12, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x48, 0x8a, 0x8b, 0xa3, 0xb0, 0x34, 0x31, 0xaf,
	0x24, 0xb3, 0xa4, 0x52, 0x82, 0x49, 0x81, 0x51, 0x83, 0x39, 0x08, 0xce, 0x57, 0x8a, 0xe2, 0xe2,
	0x81, 0x19, 0xe0, 0x9c, 0x5f, 0x94, 0x4a, 0x9a, 0x6e, 0x21, 0x19, 0x2e, 0xce, 0x62, 0xa8, 0xee,
	0x62, 0x09, 0x66, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x84, 0x80, 0x52, 0x3d, 0x97, 0x00, 0xc2, 0x71,
	0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xf2, 0x5c, 0xac, 0xa9, 0x45, 0x45, 0xf9, 0x45, 0x60,
	0x1b, 0xb8, 0x8d, 0x38, 0xf5, 0x0a, 0x92, 0xf4, 0x5c, 0x41, 0x02, 0x41, 0x10, 0x71, 0x98, 0x03,
	0x98, 0xb0, 0x3b, 0x80, 0x19, 0x9f, 0x03, 0x58, 0xd0, 0x1c, 0xa0, 0xa5, 0xc0, 0xc5, 0x0b, 0x73,
	0x40, 0x48, 0x7e, 0x41, 0x66, 0xb2, 0x10, 0x3f, 0x17, 0x37, 0x4c, 0x36, 0x3e, 0xcc, 0x50, 0x80,
	0x21, 0x89, 0x0d, 0x1c, 0x8c, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x50, 0x09, 0xbd, 0x80,
	0x69, 0x01, 0x00, 0x00,
}
